### ISSUE TITLE
Roadmap to release and beyond

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/mmm-refactor#58]
Here a simple tracker of things I'd like to be done for the release and after. I accept code contributions and suggestions!

---

## Needed before release

- [ ] Get UI feedback and tweak as needed. Goal: simplicity and usability over advanced features 
- [ ] Test at a KH
- [ ] Test migration at a KH
- [ ] Bug: Prevent music auto-start on meeting days if time is after meeting start minus 1 minute

## To implement eventually

- [ ] Add Cypress testing
- [ ] Add MP4 conversion utility to convert a meeting's media to MP4 for use with Zoom sharing (if requested)
- [ ] Implement play/pause/next/previous keyboard shortcuts (if requested)

**Comment by ux-git** [comment]
@sircharlo The docs site shuts down completely? Or will be re-written for the new app version?

**Comment by sircharlo** [comment]
> @sircharlo The docs site shuts down completely? Or will be re-written for the new app version? 

The current docs will be rendered mostly obsolete with the new version. I also find them quite "heavy". 

The new version of M³ is for the most part self-explanatory; perhaps a very simplified docs could replace the existing one; I would prefer to have most essential documentation in the app itself though, with hint text for each setting for example.

**Comment by ux-git** [comment]
Totally agree! Though, some deeper explanation like a full list of supported formats, settings guide, etc would be great to have on a documentation site, to be able to quickly link to it when needed.

Take a look at Docusaurus, it's pretty user-friendly, with nice essential design, and contribution-open. My experience with it is awesome so far. Plus, in the current GitHub pages documentation, when I open it on mobile, all the languages are mixed up with no way to fix it or to find anything. I didn't face this issue with the Docusaurus.

**Comment by sircharlo** [comment]
> Totally agree! Though, some deeper explanation like a full list of supported formats, settings guide, etc would be great to have on a documentation site, to be able to quickly link to it when needed.
> 
> Take a look at Docusaurus, it's pretty user-friendly, with nice essential design, and contribution-open. My experience with it is awesome so far. Plus, in the current GitHub pages documentation, when I open it on mobile, all the languages are mixed up with no way to fix it or to find anything. I didn't face this issue with the Docusaurus.

Very nice!

**Comment by sircharlo** [comment]
@ux-git In about 5 minutes I will release v24.7.1, which implements almost all of the UI/UX improvements you suggested!

Would you mind taking a look when you can to see if some things need to be further tweaked, or if I missed some screens?

Also, here are some dialogs that I didn't see in your mockups:
- Keyboard shortcut picker popup
- Cache clear confirmation popup
- Congregation deletion confirmation popup
- Media custom start/stop picker popup
- Video stop confirmation popup
- Media deletion popup

Do you think you could take a look and offer some feedback to make the UI consistent for these popups as well?

Thanks so much for your help!

**Comment by mrtavor** [comment]
Hi @sircharlo, we added a new page in the project in Figma called “Design review”, where we wrote some of the details along with images to make it clearer. Feel free to leave your additional comments there.

Quick overview.
Most important things are:
• Consistent icons (fill vs stroke & sizes & roundness index)
• Apply min-width and max-width for some elements
• Meeting media items: title, icon, reorder structure and logic.

There are also lower priority points that can be improved and polished. We will mention those in the corresponding priority sections later and will ping you.

**Comment by mrtavor** [comment]
What is the difference between the Media custom start/stop picker popup and Video stop confirmation popup?

**Comment by sircharlo** [comment]
> What is the difference between the Media custom start/stop picker popup and Video stop confirmation popup?

The video stop popup is what shows up when attempting to stop a video while it is playing; to prevent accidentally stopping a song for example.

The custom start-stop modal is what shows up when you click on the black HH:MM badge on a video. It allows you to set a custom start and stop time for the video (useful for when a congregation is playing a streamed public talk, they can set the start and stop times without having to cut the actual video file)

**Comment by sircharlo** [comment]
@ux-git @mrtavor I just released 24.7.2 in which the vast majority of the improvements you suggested are implemented. 
I documented a few icons that appear to be missing from the UI kit, and a few for which I could not find a use. 
When you have time, I’d love to see your thoughts on what could be still be improved or changed, or things I might have overlooked. 
Thanks again!

**Comment by alanfermtz** [comment]
Based on what I have been trying is really good. Its feels smoother.
And thanks for adding zoom in to jw org mirroring, its perfect!

Also, worth mentioning its that now I see more often images on both apps (stable, refactor) that are related to watchtower footnotes, and also the brochure love people. Its a bug? If its intended, can you make a exclude button for this cases?

**Comment by sircharlo** [comment]
> Based on what I have been trying is really good. Its feels smoother. And thanks for adding zoom in to jw org mirroring, its perfect!

Thanks so much!

> Also, worth mentioning its that now I see more often images on both apps (stable, refactor) that are related to watchtower footnotes, and also the brochure love people. Its a bug? If its intended, can you make a exclude button for this cases?

Did you look into these options in the advanced settings?

![image](https://github.com/user-attachments/assets/ba84320e-9130-4399-a642-6c6f017c90a4)

**Comment by alanfermtz** [comment]
Yes, I have that enabled
I still see all this images:

![IMG-20240808-WA0029](https://github.com/user-attachments/assets/34b274b3-b031-40af-b11f-1d54491d9467)
![IMG-20240808-WA0030](https://github.com/user-attachments/assets/f46e25b7-40da-44e3-8882-0c5e654350c3)

**Comment by mtdvlpr** [comment]
> Totally agree! Though, some deeper explanation like a full list of supported formats, settings guide, etc would be great to have on a documentation site, to be able to quickly link to it when needed.
> 
> Take a look at Docusaurus, it's pretty user-friendly, with nice essential design, and contribution-open. My experience with it is awesome so far. Plus, in the current GitHub pages documentation, when I open it on mobile, all the languages are mixed up with no way to fix it or to find anything. I didn't face this issue with the Docusaurus.

I would personally recommend [VitePress](https://vitepress.dev/), because it's Vue-based, just like M3 itself. It's very easy to setup and extremely fast!
